# QUESTION 1

In [1]:
import numpy as np
arr = np.arange(2,50,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


# QUESTION 2

In [2]:
import numpy as np
li1 = []
li2 = []
print("Enter the list 1 elements: ")  
for i in range(5): 
    ele = int(input()) 
    li1.append(ele)  
      
print("Enter the list 2 elements: ")  
for i in range(5): 
    ele = int(input()) 
    li2.append(ele)
    
arr1 = np.array(li1)
arr2 = np.array(li2)
arr3 = np.concatenate((arr1,arr2),axis =0)
print(arr3)

print(np.sort(arr3))

Enter the list 1 elements: 
1
2
3
4
5
Enter the list 2 elements: 
6
7
8
9
10
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


# QUESTION 3

In [3]:
import numpy as np
 

arr = np.array( [[ 1, 2, 3],
                 [ 4, 2, 5]] )
 
print("No. of dimensions: ", arr.ndim)
print("Size of array: ", arr.size)

No. of dimensions:  2
Size of array:  6


# QUESTION 4

In [4]:
ar1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
a2d = np.reshape(ar1, (2, 5))
a2d[0][0] = 22
print('1D Numpy array:')
print(ar1)
print('2D Numpy array:')
print(a2d)

1D Numpy array:
[22  1  2  3  4  5  6  7  8  9]
2D Numpy array:
[[22  1  2  3  4]
 [ 5  6  7  8  9]]
